spring:
  application:
    name: portfolio
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/portfolio}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        debug: false

server:
  port: 8080

kallik:
  mail:
    to: ${MAIL_TO}
    from: ${MAIL_USERNAME}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}